#include <limits.h>
extern void abort(void);
void __VERIFIER_assert(int cond) {
  if (!(cond)) {
  ERROR : { abort(); }
  }
}
extern int __VERIFIER_nondet_int(void);
extern void __VERIFIER_assume(int);
/* Generated by Frama-C */
extern void __VERIFIER_assert(int);

int main() {
  int x = 0;
  int n = __VERIFIER_nondet_int();
  if (n < 100 || n > 1000000) {
    return 0;
  }
  int y = n;
  int runtime_div;

  while (x + y <= 999999) {
    x++;
    y--;
    __VERIFIER_assert(100 <= x + n && x + n <= INT_MAX);
    __VERIFIER_assert((n - y) > 0);
    runtime_div = x / (n - y);
  }
}
